apiVersion: batch/v1
kind: Job
metadata:
  name: mlflow-gputest-job
spec:
  template:
    spec:
      containers:
      - name: mlflow-gputest-job
        image: localrepo:32000/mlflow-trainer:latest
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.local/"
        args:
          - "https://github.com/fethigurcan/yargitay-gputest.git"
      restartPolicy: Never
  backoffLimit: 4
